version: "2"

stack_defaults:
    before_init:
        - echo "testing the runner image"
        - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
stacks:
    # The key of is the immutable slug of your stack
    # which you will find in the URL.
    random-password: 
        runner_image: public.ecr.aws/spacelift/runner-terraform:v1.7.0_20240708
